language: python

sudo: required

python:
  - "3.5"

install:
-   sudo add-apt-repository -y ppa:deadsnakes/ppa
-   sudo apt-get -yq update
-   sudo apt-get -yq install python3.5 python3.5-dev python3.6 python3.6-dev python3.7 python3.7-dev
#-   pip install -r requirements-test.txt
-	pip install 'tox>=2' pylint

script:
  - ./pep8.sh
  - tox
